/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CareModeRouteImport } from './routes/care-mode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsCareSessionIdRouteImport } from './routes/reports/$careSessionId'
import { Route as RecordsNewRouteImport } from './routes/records.new'
import { Route as OnboardingParentRouteImport } from './routes/onboarding/parent'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ApiThankyouRouteImport } from './routes/api/thankyou'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ReportsCareSessionIdIndexRouteImport } from './routes/reports/$careSessionId.index'
import { Route as ReportsCareSessionIdThankYouRouteImport } from './routes/reports/$careSessionId.thank-you'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CareModeRoute = CareModeRouteImport.update({
  id: '/care-mode',
  path: '/care-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCareSessionIdRoute = ReportsCareSessionIdRouteImport.update({
  id: '/reports/$careSessionId',
  path: '/reports/$careSessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsNewRoute = RecordsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecordsRoute,
} as any)
const OnboardingParentRoute = OnboardingParentRouteImport.update({
  id: '/onboarding/parent',
  path: '/onboarding/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThankyouRoute = ApiThankyouRouteImport.update({
  id: '/api/thankyou',
  path: '/api/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCareSessionIdIndexRoute =
  ReportsCareSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReportsCareSessionIdRoute,
  } as any)
const ReportsCareSessionIdThankYouRoute =
  ReportsCareSessionIdThankYouRouteImport.update({
    id: '/thank-you',
    path: '/thank-you',
    getParentRoute: () => ReportsCareSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care-mode': typeof CareModeRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/notifications': typeof NotificationsRoute
  '/records': typeof RecordsRouteWithChildren
  '/rules': typeof RulesRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/thankyou': typeof ApiThankyouRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/records/new': typeof RecordsNewRoute
  '/reports/$careSessionId': typeof ReportsCareSessionIdRouteWithChildren
  '/reports/$careSessionId/thank-you': typeof ReportsCareSessionIdThankYouRoute
  '/reports/$careSessionId/': typeof ReportsCareSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care-mode': typeof CareModeRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/notifications': typeof NotificationsRoute
  '/records': typeof RecordsRouteWithChildren
  '/rules': typeof RulesRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/thankyou': typeof ApiThankyouRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/records/new': typeof RecordsNewRoute
  '/reports/$careSessionId/thank-you': typeof ReportsCareSessionIdThankYouRoute
  '/reports/$careSessionId': typeof ReportsCareSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care-mode': typeof CareModeRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/notifications': typeof NotificationsRoute
  '/records': typeof RecordsRouteWithChildren
  '/rules': typeof RulesRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/thankyou': typeof ApiThankyouRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/records/new': typeof RecordsNewRoute
  '/reports/$careSessionId': typeof ReportsCareSessionIdRouteWithChildren
  '/reports/$careSessionId/thank-you': typeof ReportsCareSessionIdThankYouRoute
  '/reports/$careSessionId/': typeof ReportsCareSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care-mode'
    | '/chat'
    | '/checklist'
    | '/dashboard'
    | '/family'
    | '/notifications'
    | '/records'
    | '/rules'
    | '/api/agent'
    | '/api/thankyou'
    | '/invite/$token'
    | '/onboarding/parent'
    | '/records/new'
    | '/reports/$careSessionId'
    | '/reports/$careSessionId/thank-you'
    | '/reports/$careSessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care-mode'
    | '/chat'
    | '/checklist'
    | '/dashboard'
    | '/family'
    | '/notifications'
    | '/records'
    | '/rules'
    | '/api/agent'
    | '/api/thankyou'
    | '/invite/$token'
    | '/onboarding/parent'
    | '/records/new'
    | '/reports/$careSessionId/thank-you'
    | '/reports/$careSessionId'
  id:
    | '__root__'
    | '/'
    | '/care-mode'
    | '/chat'
    | '/checklist'
    | '/dashboard'
    | '/family'
    | '/notifications'
    | '/records'
    | '/rules'
    | '/api/agent'
    | '/api/thankyou'
    | '/invite/$token'
    | '/onboarding/parent'
    | '/records/new'
    | '/reports/$careSessionId'
    | '/reports/$careSessionId/thank-you'
    | '/reports/$careSessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareModeRoute: typeof CareModeRoute
  ChatRoute: typeof ChatRoute
  ChecklistRoute: typeof ChecklistRoute
  DashboardRoute: typeof DashboardRoute
  FamilyRoute: typeof FamilyRoute
  NotificationsRoute: typeof NotificationsRoute
  RecordsRoute: typeof RecordsRouteWithChildren
  RulesRoute: typeof RulesRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiThankyouRoute: typeof ApiThankyouRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingParentRoute: typeof OnboardingParentRoute
  ReportsCareSessionIdRoute: typeof ReportsCareSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-mode': {
      id: '/care-mode'
      path: '/care-mode'
      fullPath: '/care-mode'
      preLoaderRoute: typeof CareModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$careSessionId': {
      id: '/reports/$careSessionId'
      path: '/reports/$careSessionId'
      fullPath: '/reports/$careSessionId'
      preLoaderRoute: typeof ReportsCareSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/new': {
      id: '/records/new'
      path: '/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof RecordsNewRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/onboarding/parent': {
      id: '/onboarding/parent'
      path: '/onboarding/parent'
      fullPath: '/onboarding/parent'
      preLoaderRoute: typeof OnboardingParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thankyou': {
      id: '/api/thankyou'
      path: '/api/thankyou'
      fullPath: '/api/thankyou'
      preLoaderRoute: typeof ApiThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$careSessionId/': {
      id: '/reports/$careSessionId/'
      path: '/'
      fullPath: '/reports/$careSessionId/'
      preLoaderRoute: typeof ReportsCareSessionIdIndexRouteImport
      parentRoute: typeof ReportsCareSessionIdRoute
    }
    '/reports/$careSessionId/thank-you': {
      id: '/reports/$careSessionId/thank-you'
      path: '/thank-you'
      fullPath: '/reports/$careSessionId/thank-you'
      preLoaderRoute: typeof ReportsCareSessionIdThankYouRouteImport
      parentRoute: typeof ReportsCareSessionIdRoute
    }
  }
}

interface RecordsRouteChildren {
  RecordsNewRoute: typeof RecordsNewRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsNewRoute: RecordsNewRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

interface ReportsCareSessionIdRouteChildren {
  ReportsCareSessionIdThankYouRoute: typeof ReportsCareSessionIdThankYouRoute
  ReportsCareSessionIdIndexRoute: typeof ReportsCareSessionIdIndexRoute
}

const ReportsCareSessionIdRouteChildren: ReportsCareSessionIdRouteChildren = {
  ReportsCareSessionIdThankYouRoute: ReportsCareSessionIdThankYouRoute,
  ReportsCareSessionIdIndexRoute: ReportsCareSessionIdIndexRoute,
}

const ReportsCareSessionIdRouteWithChildren =
  ReportsCareSessionIdRoute._addFileChildren(ReportsCareSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareModeRoute: CareModeRoute,
  ChatRoute: ChatRoute,
  ChecklistRoute: ChecklistRoute,
  DashboardRoute: DashboardRoute,
  FamilyRoute: FamilyRoute,
  NotificationsRoute: NotificationsRoute,
  RecordsRoute: RecordsRouteWithChildren,
  RulesRoute: RulesRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiThankyouRoute: ApiThankyouRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingParentRoute: OnboardingParentRoute,
  ReportsCareSessionIdRoute: ReportsCareSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
